# JVM 参数：给 Gradle/Kotlin 编译足够内存
org.gradle.jvmargs=-Xmx3072m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

# AndroidX
android.useAndroidX=true
android.nonTransitiveRClass=true

# Kotlin
kotlin.code.style=official

# 本地代理（Clash 7897）；不使用代理时可删除本段
systemProp.http.proxyHost=127.0.0.1
systemProp.http.proxyPort=7897
systemProp.https.proxyHost=127.0.0.1
systemProp.https.proxyPort=7897
systemProp.http.nonProxyHosts=localhost|127.0.0.1|maven.aliyun.com|mirrors.cloud.tencent.com
systemProp.https.nonProxyHosts=localhost|127.0.0.1|maven.aliyun.com|mirrors.cloud.tencent.com
